// Code generated by protoc-gen-go. DO NOT EDIT.
// source: firewall_event.proto

package ExchangeMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	SrcIpAddr            uint32               `protobuf:"fixed32,1,opt,name=src_ip_addr,json=srcIpAddr,proto3" json:"src_ip_addr,omitempty"`
	DstIpAddr            uint32               `protobuf:"fixed32,2,opt,name=dst_ip_addr,json=dstIpAddr,proto3" json:"dst_ip_addr,omitempty"`
	SrcPort              uint32               `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort              uint32               `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	DeviceId             uint32               `protobuf:"varint,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Action               uint32               `protobuf:"varint,7,opt,name=action,proto3" json:"action,omitempty"`
	AclRuleId            uint32               `protobuf:"varint,8,opt,name=acl_rule_id,json=aclRuleId,proto3" json:"acl_rule_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_firewall_event_1bf180f03d8cff74, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSrcIpAddr() uint32 {
	if m != nil {
		return m.SrcIpAddr
	}
	return 0
}

func (m *Event) GetDstIpAddr() uint32 {
	if m != nil {
		return m.DstIpAddr
	}
	return 0
}

func (m *Event) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Event) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *Event) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *Event) GetDeviceId() uint32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *Event) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *Event) GetAclRuleId() uint32 {
	if m != nil {
		return m.AclRuleId
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "ExchangeMessage.Event")
}

func init() {
	proto.RegisterFile("firewall_event.proto", fileDescriptor_firewall_event_1bf180f03d8cff74)
}

var fileDescriptor_firewall_event_1bf180f03d8cff74 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x07, 0x70, 0x3a, 0xdd, 0xaf, 0x54, 0x11, 0x8a, 0x48, 0x9d, 0xa0, 0xc5, 0x53, 0x4f, 0x1d,
	0xe8, 0xd9, 0x83, 0x87, 0x1d, 0x7a, 0x10, 0xa4, 0xe8, 0x39, 0x64, 0x79, 0x6f, 0x35, 0x90, 0x35,
	0x21, 0x79, 0x9d, 0xfe, 0x1b, 0xfe, 0xc7, 0x92, 0x64, 0xf3, 0x98, 0x7c, 0xde, 0xf7, 0xe5, 0x1b,
	0x76, 0xbd, 0x53, 0x0e, 0xbf, 0x85, 0xd6, 0x1c, 0x0f, 0x38, 0x50, 0x63, 0x9d, 0x21, 0x53, 0x5c,
	0x6d, 0x7e, 0xe4, 0x97, 0x18, 0x7a, 0x7c, 0x43, 0xef, 0x45, 0x8f, 0xab, 0x87, 0xde, 0x98, 0x5e,
	0xe3, 0x3a, 0xf2, 0x76, 0xdc, 0xad, 0x49, 0xed, 0xd1, 0x93, 0xd8, 0xdb, 0x94, 0x78, 0xfc, 0x9d,
	0xb0, 0xe9, 0x26, 0x6c, 0x28, 0xee, 0x59, 0xee, 0x9d, 0xe4, 0xca, 0x72, 0x01, 0xe0, 0xca, 0xac,
	0xca, 0xea, 0x79, 0xb7, 0xf4, 0x4e, 0xb6, 0xf6, 0x15, 0xc0, 0x05, 0x07, 0x4f, 0xff, 0x3e, 0x49,
	0x0e, 0x9e, 0x8e, 0x7e, 0xcb, 0x16, 0x21, 0x6f, 0x8d, 0xa3, 0xf2, 0xac, 0xca, 0xea, 0xcb, 0x6e,
	0xee, 0x9d, 0x7c, 0x37, 0x8e, 0x02, 0x85, 0x68, 0xa4, 0xf3, 0x44, 0xe0, 0x29, 0xd2, 0x0b, 0xbb,
	0xd0, 0xc2, 0x13, 0x1f, 0x2d, 0x08, 0x42, 0x28, 0xa7, 0x55, 0x56, 0xe7, 0x4f, 0xab, 0x26, 0xf5,
	0x6e, 0x4e, 0xbd, 0x9b, 0x8f, 0x53, 0xef, 0x2e, 0x0f, 0xf3, 0x9f, 0x69, 0xbc, 0xb8, 0x63, 0x4b,
	0xc0, 0x83, 0x92, 0xc8, 0x15, 0x94, 0xb3, 0xb8, 0x7a, 0x91, 0x2e, 0x5a, 0x28, 0x6e, 0xd8, 0x4c,
	0x48, 0x52, 0x66, 0x28, 0xe7, 0x51, 0x8e, 0xa7, 0xf0, 0x13, 0x21, 0x35, 0x77, 0xa3, 0x8e, 0xb1,
	0x45, 0xc4, 0xa5, 0x90, 0xba, 0x1b, 0x35, 0xb6, 0xb0, 0x9d, 0xc5, 0x57, 0x9f, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xbe, 0xd2, 0x8d, 0x5a, 0x64, 0x01, 0x00, 0x00,
}
