// Code generated by protoc-gen-go. DO NOT EDIT.
// source: firewall_event.proto

package ExchangeMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	SrcIpAddr            uint32   `protobuf:"fixed32,1,opt,name=src_ip_addr,json=srcIpAddr,proto3" json:"src_ip_addr,omitempty"`
	DstIpAddr            uint32   `protobuf:"fixed32,2,opt,name=dst_ip_addr,json=dstIpAddr,proto3" json:"dst_ip_addr,omitempty"`
	SrcPort              uint32   `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort              uint32   `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_firewall_event_dbc96d5b020db5eb, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSrcIpAddr() uint32 {
	if m != nil {
		return m.SrcIpAddr
	}
	return 0
}

func (m *Event) GetDstIpAddr() uint32 {
	if m != nil {
		return m.DstIpAddr
	}
	return 0
}

func (m *Event) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Event) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "ExchangeMessage.Event")
}

func init() {
	proto.RegisterFile("firewall_event.proto", fileDescriptor_firewall_event_dbc96d5b020db5eb)
}

var fileDescriptor_firewall_event_dbc96d5b020db5eb = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xcb, 0x2c, 0x4a,
	0x2d, 0x4f, 0xcc, 0xc9, 0x89, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x28, 0x29, 0x2d, 0xc9, 0x2f, 0xca, 0x4c, 0xcc, 0x51, 0xaa, 0xe5, 0x62, 0x75, 0x05,
	0x49, 0x08, 0xc9, 0x71, 0x71, 0x17, 0x17, 0x25, 0xc7, 0x67, 0x16, 0xc4, 0x27, 0xa6, 0xa4, 0x14,
	0x49, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x07, 0x71, 0x16, 0x17, 0x25, 0x7b, 0x16, 0x38, 0xa6, 0xa4,
	0x14, 0x81, 0xe4, 0x53, 0x8a, 0x4b, 0xe0, 0xf2, 0x4c, 0x10, 0xf9, 0x94, 0xe2, 0x12, 0xa8, 0xbc,
	0x24, 0x17, 0x07, 0x48, 0x7f, 0x41, 0x7e, 0x51, 0x89, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6f, 0x10,
	0x7b, 0x71, 0x51, 0x72, 0x40, 0x7e, 0x51, 0x09, 0x48, 0x0a, 0xa4, 0x15, 0x2c, 0xc5, 0x02, 0x91,
	0x4a, 0x29, 0x2e, 0x01, 0x49, 0x25, 0xb1, 0x81, 0xdd, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xab, 0x53, 0x29, 0xa6, 0xa7, 0x00, 0x00, 0x00,
}
